In [2]:
from numpy import argmax

In [3]:
import pandas as pd


In [4]:
from sklearn.datasets import load_iris

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [7]:
iris=load_iris()

In [8]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [9]:
x=iris.data[:,:].astype('float32')
y=iris.target

In [10]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [11]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [12]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)

In [13]:
n_feature=x_train.shape[1]
print('Number of Features:',n_feature)

Number of Features: 4


In [14]:
model=Sequential()


In [15]:
model.add(Dense(10,activation='relu',kernel_initializer='he_normal',input_shape=(n_feature,)))
model.add(Dense(8,activation='relu',kernel_initializer='he_normal'))
model.add(Dense(3,activation='softmax'))

In [16]:
model.compile(optimizer="adam",loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [17]:
model.fit(x_train,y_train,epochs=150,batch_size=32)

Epoch 1/150
4/4 [==============================] - 1s 7ms/step - loss: 7.9110 - accuracy: 0.3482
Epoch 2/150
4/4 [==============================] - 0s 5ms/step - loss: 7.3838 - accuracy: 0.3482
Epoch 3/150
4/4 [==============================] - 0s 6ms/step - loss: 6.8695 - accuracy: 0.3482
Epoch 4/150
4/4 [==============================] - 0s 5ms/step - loss: 6.3499 - accuracy: 0.3482
Epoch 5/150
4/4 [==============================] - 0s 6ms/step - loss: 5.8187 - accuracy: 0.3482
Epoch 6/150
4/4 [==============================] - 0s 6ms/step - loss: 5.3069 - accuracy: 0.3482
Epoch 7/150
4/4 [==============================] - 0s 7ms/step - loss: 4.7464 - accuracy: 0.3482
Epoch 8/150
4/4 [==============================] - 0s 5ms/step - loss: 4.1980 - accuracy: 0.3482
Epoch 9/150
4/4 [==============================] - 0s 6ms/step - loss: 3.6539 - accuracy: 0.3482
Epoch 10/150
4/4 [==============================] - 0s 6ms/step - loss: 3.1235 - accuracy: 0.3482
Epoch 11/150
4/4 [===========

In [18]:
new_data=[5.1,3.5,1.4,0.2]
y_pred=model.predict([new_data])

1/1 [==============================] - 0s 181ms/step


In [19]:
print(y_pred)

[[0.9772932  0.0215489  0.00115796]]


In [22]:
[[0.9772932  0.0215489  0.00115796]]

SyntaxError: invalid syntax. Perhaps you forgot a comma? (<ipython-input-22-d5935934d415>, line 1)